@endpoint = http://app1.console.smallsaas.cn:8001

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDk2NjgxMDYsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0OTkyNzMwNn0.iLGksJKrVC4l-fyFSYYT3c6m4fDZ2d7HCRNATLajxDmFA6X1-kq6riT5i89DU81T45sMTd2-JvXFgmYoviRjow

#### 获取动态页面列表
GET {{endpoint}}/api/crud/lowMainPage/lowMainPages?pageNum=1&pageSize=10
Authorization:Bearer {{token}}


#### 添加页面
POST {{endpoint}}/api/crud/lowMainPage/lowMainPages
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "pageName": "TestPage002", 
    "pageTitle": "标题", 
    "formAddTitle": "新增", 
    "formViewTitle": "查看", 
    "formEditTitle": "编辑", 
    "columnAlign": "left", 
    "apiEndpoint": "/api", 
    "contentLayout": "Content", 
    "pageMinWidth": "", 
    "formDefaultContentLayout": "TitleContent", 
    "searchType": "MoreSearch", 
    "searchButtonType": "text", 
    "contentItemContainerStyle": ""
}

#### 编辑页面
PUT {{endpoint}}/api/crud/lowMainPage/lowMainPages/6
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "formAddTitle": "新增", 
    "searchType": "MoreSearch", 
    "pageTitle": "标题", 
    "formViewTitle": "查看", 
    "formDefaultContentLayout": "TitleContent", 
    "lowOperationss": [ ], 
    "lowActionss": [ ], 
    "pageName": "TestPage002", 
    "lowFilterss": [ ], 
    "lowFieldss": [ ], 
    "contentLayout": "Content", 
    "searchButtonType": "text", 
    "apiEndpoint": "/api", 
    "columnAlign": "center", 
    "formEditTitle": "编辑", 
    "id": 6, 
    "contentItemContainerStyle": ""
}


#### 加载字段
POST {{endpoint}}/addLowFields
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "endpoint":"http://app1.console.smallsaas.cn:8001",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDk2Njg3MTQsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0OTkyNzkxNH0.DDZBRJE6DE3IyS03JkHXFP4oWXM54aD95svtlXQsBExmp6EJFYsNndybvSfFJoDEuGwMePeBVTwb9O1uXEOi0A",
    "pageId":"6",
    "originApi":"/api/crud/lowActions/lowActionses"
}


#### 获取页面数据详情
GET {{endpoint}}/api/crud/lowMainPage/lowMainPages/6
Authorization:Bearer {{token}}


### 转换成页面配置
POST {{endpoint}}/toconfig
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "formAddTitle": "新增", 
    "searchType": "MoreSearch", 
    "pageTitle": "标题", 
    "formViewTitle": "查看", 
    "formDefaultContentLayout": "TitleContent", 
    "lowOperationss": [ ], 
    "lowActionss": [ ], 
    "pageName": "TestPage002", 
    "lowFilterss": [ ], 
    "lowFieldss": [
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "modalLayout", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "modalLayout", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "modalLayout", 
            "id": 29, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "modalLayout", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "modalLayout", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "modalTitle", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "modalTitle", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "modalTitle", 
            "id": 30, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "modalTitle", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "modalTitle", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "modalWidth", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "modalWidth", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "modalWidth", 
            "id": 31, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "modalWidth", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "modalWidth", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "pageId", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "pageId", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "pageId", 
            "id": 32, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "pageId", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "pageId", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "path", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "path", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "path", 
            "id": 33, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "path", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "path", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "requestApi", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "requestApi", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "requestApi", 
            "id": 34, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "requestApi", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "requestApi", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "requestBody", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "requestBody", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "requestBody", 
            "id": 35, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "requestBody", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "requestBody", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "requestMethod", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "requestMethod", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "requestMethod", 
            "id": 36, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "requestMethod", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "requestMethod", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "requestOptions", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "requestOptions", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "requestOptions", 
            "id": 37, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "requestOptions", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "requestOptions", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "requestRefreshApi", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "requestRefreshApi", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "requestRefreshApi", 
            "id": 38, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "requestRefreshApi", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "requestRefreshApi", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "title", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "title", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "title", 
            "id": 39, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "title", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "title", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }, 
        {
            "listColumnMultiKeys": "", 
            "fieldBinding": "type", 
            "listColumnWidth": 0, 
            "listColumnKey": "", 
            "fieldValueOptions": "", 
            "formInputType": "input", 
            "formViewType": "plain", 
            "listFontSize": 0, 
            "fieldScopes": "page,table,edit,add,view", 
            "formFieldQuestion": "", 
            "fieldItemName": "type", 
            "fieldValueFilter": "", 
            "formFieldHint": "", 
            "listFontColor": "", 
            "fieldLabel": "type", 
            "id": 40, 
            "formFieldTips": "", 
            "listColumnLayout": "", 
            "formFieldTitle": "type", 
            "formViewOptions": "", 
            "listColumnOptions": "", 
            "pageId": 6, 
            "listFontWeight": "", 
            "listColumnFormat": "", 
            "listColumnAlign": "left", 
            "listColumnName": "type", 
            "formInputOptions": "", 
            "formInputRequired": 0, 
            "listColumnType": "plain", 
            "listColumnReference": ""
        }
    ], 
    "contentLayout": "Content", 
    "searchButtonType": "text", 
    "apiEndpoint": "/api/crud/lowActions/lowActionses", 
    "columnAlign": "center", 
    "formEditTitle": "编辑", 
    "id": 6, 
    "contentItemContainerStyle": ""
}


###获取原始数据并创建页面
POST {{endpoint}}/toField
Authorization:Bearer {{token}}
Content-Type: application/json

{
	"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJhcHBpZCI6IiIsImlhdCI6MTcyNzE2MTU2NiwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNzI3NDIwNzY2fQ.kKuoD69KqvmSXa-lfAB0ASqZQJuPJ6vp6NmpYVXmxRjhorSY8jbAJUNFHCGuQeTnE_aUYG0lE009XumnoMEQGA",
	"data": {
		"pageId": "47",
		"path": "/tenantManage/tenantManage",
		"menuId": "47"
	}
}